### ISSUE TITLE
Script get's stuck for large network

### ISSUE THREAD

**Issue by rohanghige** [brianpursley/sorting-network#1]
Created a concatenated network using existing 16-input network
`yes examples/16-input.cn | head -n 100 | xargs cat > new.cn`

Tested its correctness with script
`./sortingnetwork.py --input new.cn --check`

It get's stuck for long time. Is there any way to show progress or current status?

**Comment by brianpursley** [comment]
Hi @rohanghige 

I never really ran it on a network that big, but I like your idea.

I just added a `--show-progress` command line argument which will output the % complete while checking.

Also, you may want to check out [sorting-network-go](https://github.com/brianpursley/sorting-network-go) which is a Go implementation with the same functionality, but is MUCH faster due to the use of go routines.

Example:

Python version takes ~55 seconds to check:
```
$ time ./sortingnetwork.py --input new.cn --check
It is a sorting network!

real	0m55.731s
user	0m55.720s
sys	0m0.009s
```

Go version takes < 1 second to check:
```
$ time go run sorting-network.go --input new.cn --check
It is a sorting network!

real	0m0.363s
user	0m2.366s
sys	0m0.138s
```

**Comment by rohanghige** [comment]
Thank you @brianpursley for such a quick response. I tried your change, and it works really great. I will try your go implementation also. Salute :)
